import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<meta charSet="UTF-8" />
			<meta http-Equiv="X-UA-Compatible" content="IE=edge" />
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />

			<title>Coming Soon... - mxtn.pl</title>

			<meta name="author" content="MixeroTN" />
			<meta name="description" content="MixeroTN's Portfolio website." />

			<meta name="robots" content="index, follow" />
			<meta name="application-name" content="Portfolio - mxtn.pl" />
			<meta name="mobile-web-app-capable" content="yes" />
			<meta name="theme-color" content="#fc6d27" />

			<meta name="apple-mobile-web-app-capable" content="yes" />
			<meta name="apple-mobile-web-app-status-bar-style" content="default" />
			<meta name="apple-mobile-web-app-title" content="Portfolio - mxtn.pl" />
			<meta name="msapplication-TileColor" content="#da532c" />

			<meta property="og:title" content="Portfolio - mxtn.pl" />
			<meta property="og:description" content="MixeroTN's Portfolio website." />
			<meta property="og:url" content="https://mxtn.pl" />
			<meta property="og:type" content="website" />

			<meta name="twitter:card" content="summary" />
			<meta name="twitter:title" content="Portfolio - mxtn.pl" />
			<meta
				name="twitter:description"
				content="MixeroTN's Portfolio website."
			/>

			<body className={inter.className}>{children}</body>
		</html>
	);
}
